---
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description:
# Template file for docker-compose.yml, which is used in testing.

version: '3'
services:
  kibana:
    container_name: opendistroforelasticsearch-kibana-test
    image: humanmade/altis-local-server-kibana:edge
    ports:
      - 5601:5601
    networks: [opendistroforelasticsearch]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  elasticsearch:
    container_name: opendistroforelasticsearch-test
    image: humanmade/altis-local-server-elasticsearch:edge
    networks: [opendistroforelasticsearch]
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
networks:
  opendistroforelasticsearch:
